In [3]:
import numpy as np
#ex 7
shape = (2, 2, 2, 2, 2)
a = np.zeros(shape)
for i in range(2):
  for j in range(2):
    for p in range(2):
      for t in range(2):
        for l in range(2):
          a[l][p][t][i][j] = 1 * (i+1)-3 * (j+1)-3 * (t+1) + 2 * (l+1)
print(a)

[[[[[-3. -6.]
    [-2. -5.]]

   [[-6. -9.]
    [-5. -8.]]]


  [[[-3. -6.]
    [-2. -5.]]

   [[-6. -9.]
    [-5. -8.]]]]



 [[[[-1. -4.]
    [ 0. -3.]]

   [[-4. -7.]
    [-3. -6.]]]


  [[[-1. -4.]
    [ 0. -3.]]

   [[-4. -7.]
    [-3. -6.]]]]]


In [21]:
#ex 8
shape = (2, 2, 2, 2, 2)
a = np.zeros(shape)
for m in range(2):
  for j in range(2):
    for p in range(2):
      for t in range(2):
        for k in range(2):
          a[k][p][t][m][j] = 3 * (m+1) - 2 * (j+1) - 2 * (p+1) - (t+1) - (k+1)
print(a)

[[[[[-3. -5.]
    [ 0. -2.]]

   [[-4. -6.]
    [-1. -3.]]]


  [[[-5. -7.]
    [-2. -4.]]

   [[-6. -8.]
    [-3. -5.]]]]



 [[[[-4. -6.]
    [-1. -3.]]

   [[-5. -7.]
    [-2. -4.]]]


  [[[-6. -8.]
    [-3. -5.]]

   [[-7. -9.]
    [-4. -6.]]]]]


In [11]:
#ex 17
a = np.array([[6, -3, -2], [4, 4, 1], [-3, 3, -2]])
b = np.array([-5, -1, -1])
ab = np.tensordot(a, b, axes=0)
shape = (3, 3, 3)
c = np.zeros(shape)
for k in range(3):
  for p in range(3):
    for r in range(3):
      c[r][k][p] = 0.5 * (ab[r][k][p] + ab[k][p][r] + ab[p][r][k] - ab[p][k][r] - ab[r][p][k] - ab[k][r][p])
print(c)

[[[ 0.  0.  0.]
  [ 0.  0.  9.]
  [ 0. -9.  0.]]

 [[ 0.  0. -9.]
  [ 0.  0.  0.]
  [ 9.  0.  0.]]

 [[ 0.  9.  0.]
  [-9.  0.  0.]
  [ 0.  0.  0.]]]


In [12]:
#ex 18
b = np.array([[-5, 4, -4], [3, 1, -6], [-1, 2, 0]])
a = np.array([3, -4, 6])
ab = np.tensordot(a, b, axes=0)
shape = (3, 3, 3)
c = np.zeros(shape)
for k in range(3):
  for p in range(3):
    for r in range(3):
      c[r][k][p] = 0.5 * (ab[r][k][p] + ab[k][p][r] + ab[p][r][k] - ab[p][k][r] - ab[r][p][k] - ab[k][r][p])
print(c)

[[[  0.   0.   0.]
  [  0.   0. -15.]
  [  0.  15.   0.]]

 [[  0.   0.  15.]
  [  0.   0.   0.]
  [-15.   0.   0.]]

 [[  0. -15.   0.]
  [ 15.   0.   0.]
  [  0.   0.   0.]]]


In [13]:
#ex 19
a = np.array([[3, 2, 0], [-2, -6, -3], [-4, 2, 2]])
b = np.array([1, -2, -1])
ab = np.tensordot(a, b, axes=0)
shape = (3, 3, 3)
c = np.zeros(shape)
for k in range(3):
  for p in range(3):
    for r in range(3):
      c[r][k][p] = 0.5 * (ab[r][k][p] + ab[k][p][r] + ab[p][r][k] - ab[p][k][r] - ab[r][p][k] - ab[k][r][p])
print(c)

[[[ 0.   0.   0. ]
  [ 0.   0.  -0.5]
  [ 0.   0.5  0. ]]

 [[ 0.   0.   0.5]
  [ 0.   0.   0. ]
  [-0.5  0.   0. ]]

 [[ 0.  -0.5  0. ]
  [ 0.5  0.   0. ]
  [ 0.   0.   0. ]]]


In [17]:
#ex 20
b = np.array([[2, 2, -4], [5, 2, 5], [1, 0, -1]])
a = np.array([-5, 1, 5])
ab = np.tensordot(a, b, axes=0)
shape = (3, 3, 3)
c = np.zeros(shape)
for k in range(3):
  for p in range(3):
    for r in range(3):
      c[r][k][p] = 0.5 * (ab[r][k][p] + ab[k][p][r] + ab[p][r][k] - ab[p][k][r] - ab[r][p][k] - ab[k][r][p])
print(c)

[[[  0.    0.    0. ]
  [  0.    0.  -17.5]
  [  0.   17.5   0. ]]

 [[  0.    0.   17.5]
  [  0.    0.    0. ]
  [-17.5   0.    0. ]]

 [[  0.  -17.5   0. ]
  [ 17.5   0.    0. ]
  [  0.    0.    0. ]]]


In [6]:
#ex 13
a = np.array([[[-1, -5, -4], [-6, -2, -6], [1, -1, 3]],
              [[-4, 3, 5], [4, 0, 0], [-2, 4, -5]],
              [[0, 3, -1], [-3, 0, 4], [-4, 5, 2]]])
shape = (3, 3, 3)
b = np.zeros(shape)
for q in range(3):
  for l in range(3):
    for j in range(3):
      b[j][q][l] = 0.5 * (a[j][q][l] - a[q][j][l])
print(b)

[[[ 0.   0.   0. ]
  [-1.  -2.5 -5.5]
  [ 0.5 -2.   2. ]]

 [[ 1.   2.5  5.5]
  [ 0.   0.   0. ]
  [ 0.5  2.  -4.5]]

 [[-0.5  2.  -2. ]
  [-0.5 -2.   4.5]
  [ 0.   0.   0. ]]]


In [7]:
#ex 14
a = np.array([[[3, -3, 3], [-1, -3, 0], [0, -4, 5]],
              [[0, -1, 0], [-3, -1, -2], [-1, -5, 1]],
              [[3, 4, -6], [3, 3, -3], [-4, 2, -5]]])
shape = (3, 3, 3)
b = np.zeros(shape)
for j in range(3):
  for i in range(3):
    for q in range(3):
      b[q][j][i] = 0.5 * (a[q][j][i] - a[j][q][i])
print(b)

[[[ 0.   0.   0. ]
  [-0.5 -1.   0. ]
  [-1.5 -4.   5.5]]

 [[ 0.5  1.   0. ]
  [ 0.   0.   0. ]
  [-2.  -4.   2. ]]

 [[ 1.5  4.  -5.5]
  [ 2.   4.  -2. ]
  [ 0.   0.   0. ]]]


In [8]:
#ex 15
a = np.array([[[1, -6, 0], [-3, -3, -5], [1, -3, -4]],
              [[0, -5, 2], [-1, -4, 2], [-4, -3, 5]],
              [[0, -2, 4], [-6, -6, -4], [-5, 3, 3]]])
shape = (3, 3, 3)
b = np.zeros(shape)
for m in range(3):
  for k in range(3):
    for q in range(3):
      b[k][m][q] = 0.5 * (a[k][m][q] - a[q][m][k])
print(b)

[[[ 0.  -3.   0. ]
  [ 0.  -1.   0.5]
  [ 0.   0.5  0.5]]

 [[ 3.   0.   2. ]
  [ 1.   0.   4. ]
  [-0.5  0.   1. ]]

 [[ 0.  -2.   0. ]
  [-0.5 -4.   0. ]
  [-0.5 -1.   0. ]]]


In [9]:
#ex 16
a = np.array([[[-5, 3, 1], [0, 5, -2], [0, -5, 4]],
              [[-1, 5, 6], [2, 2, -3], [-4, 0, 5]],
              [[0, 0, -1], [2, -1, -4], [-3, 3, 1]]])
shape = (3, 3, 3)
b = np.zeros(shape)
for j in range(3):
  for l in range(3):
    for q in range(3):
      b[l][j][q] = 0.5 * (a[l][j][q] - a[l][q][j])
print(b)

[[[ 0.   1.5  0.5]
  [-1.5  0.   1.5]
  [-0.5 -1.5  0. ]]

 [[ 0.   1.5  5. ]
  [-1.5  0.  -1.5]
  [-5.   1.5  0. ]]

 [[ 0.  -1.   1. ]
  [ 1.   0.  -3.5]
  [-1.   3.5  0. ]]]


In [22]:
#ex 9
a = np.array([[[[-6, -5, 4], [-6, -5, -3], [-2, 5, 2]], 
              [[0, 4, -5], [5, -2, 1], [5, -2, 5]], 
              [[-1, 4, -1], [4, -3, 4], [-1, 1, 3]]],
              [[[-6, -3, -5], [6, 0, 0], [-4, 3, -2]], 
              [[-5, 3, 5], [4, 3, 2], [4, -2, -6]], 
              [[0, -2, 1], [4, -3, 5], [3, 2, -4]]], 
              [[[-1, 5, 4], [5, 3, 4], [-4, -1, -1]], 
              [[4, 1, 4], [0, -3, 3], [-3, 3, -2]], 
              [[4, 1, -6], [-1, 6, -6], [1, -1, 4]]]])
shape = (3, 3, 3, 3)
b = np.zeros(shape)
for j in range(3):
    for i in range(3):
      for m in range(3):
        for k in range(3):
            b[j][i][k][m] = a[i][m][k][j]
print(b)

[[[[-6.  0. -1.]
   [-6.  5.  4.]
   [-2.  5. -1.]]

  [[-6. -5.  0.]
   [ 6.  4.  4.]
   [-4.  4.  3.]]

  [[-1.  4.  4.]
   [ 5.  0. -1.]
   [-4. -3.  1.]]]


 [[[-5.  4.  4.]
   [-5. -2. -3.]
   [ 5. -2.  1.]]

  [[-3.  3. -2.]
   [ 0.  3. -3.]
   [ 3. -2.  2.]]

  [[ 5.  1.  1.]
   [ 3. -3.  6.]
   [-1.  3. -1.]]]


 [[[ 4. -5. -1.]
   [-3.  1.  4.]
   [ 2.  5.  3.]]

  [[-5.  5.  1.]
   [ 0.  2.  5.]
   [-2. -6. -4.]]

  [[ 4.  4. -6.]
   [ 4.  3. -6.]
   [-1. -2.  4.]]]]


In [23]:
#ex 10
a = np.array([[[[5, 5, -4], [5, -1, 3], [2, -4, -6]], 
              [[-1, 2, -6], [-6, -1, 1], [3, 2, -1]], 
              [[2, 4, -1], [-6, -2, -1], [4, 1, -5]]],
              [[[4, -2, -2], [-3, 6, -1], [5, 4, 1]], 
              [[0, 3, -3], [3, -2, -2], [2, 3, 5]], 
              [[-1, 3, -6], [2, -6, 0], [5, -5, -3]]], 
              [[[4, -6, -5], [-1, -3, -5], [3, -4, -4]], 
              [[-2, -5, -2], [-3, -4, 5], [3, -3, 5]], 
              [[1, 4, 5], [4, -2, 4], [5, 5, 3]]]])
shape = (3, 3, 3, 3)
b = np.zeros(shape)
for j in range(3):
    for i in range(3):
      for m in range(3):
        for k in range(3):
            b[j][i][m][k] = a[k][i][j][m]
print(b)

[[[[ 5.  4.  4.]
   [ 5. -2. -6.]
   [-4. -2. -5.]]

  [[-1.  0. -2.]
   [ 2.  3. -5.]
   [-6. -3. -2.]]

  [[ 2. -1.  1.]
   [ 4.  3.  4.]
   [-1. -6.  5.]]]


 [[[ 5. -3. -1.]
   [-1.  6. -3.]
   [ 3. -1. -5.]]

  [[-6.  3. -3.]
   [-1. -2. -4.]
   [ 1. -2.  5.]]

  [[-6.  2.  4.]
   [-2. -6. -2.]
   [-1.  0.  4.]]]


 [[[ 2.  5.  3.]
   [-4.  4. -4.]
   [-6.  1. -4.]]

  [[ 3.  2.  3.]
   [ 2.  3. -3.]
   [-1.  5.  5.]]

  [[ 4.  5.  5.]
   [ 1. -5.  5.]
   [-5. -3.  3.]]]]


In [24]:
#ex 11
a = np.array([[[[5, -6, -1], [1, 4, 2], [2, 0, -1]], 
              [[3, 0, -2], [-5, 4, 3], [4, 4, -1]], 
              [[0, 0, -1], [-6, 1, 1], [1, -4, -5]]],
              [[[-4, 2, -5], [2, -1, -4], [6, -6, 3]], 
              [[3, -2, -6], [2, -2, 0], [4, -1, 2]], 
              [[2, -3, 5], [-4, 1, 0], [-3, 2, -1]]], 
              [[[0, 3, 0], [2, 4, -2], [5, 2, 1]], 
              [[1, -6, -2], [3, -6, 2], [-1, -5, -5]], 
              [[5, -3, -1], [3, 3, -4], [3, 2, 3]]]])
shape = (3, 3, 3, 3)
b = np.zeros(shape)
for l in range(3):
    for i in range(3):
      for m in range(3):
        for k in range(3):
            b[m][l][k][i] = a[k][m][l][i]
print(b)

[[[[ 5. -6. -1.]
   [-4.  2. -5.]
   [ 0.  3.  0.]]

  [[ 1.  4.  2.]
   [ 2. -1. -4.]
   [ 2.  4. -2.]]

  [[ 2.  0. -1.]
   [ 6. -6.  3.]
   [ 5.  2.  1.]]]


 [[[ 3.  0. -2.]
   [ 3. -2. -6.]
   [ 1. -6. -2.]]

  [[-5.  4.  3.]
   [ 2. -2.  0.]
   [ 3. -6.  2.]]

  [[ 4.  4. -1.]
   [ 4. -1.  2.]
   [-1. -5. -5.]]]


 [[[ 0.  0. -1.]
   [ 2. -3.  5.]
   [ 5. -3. -1.]]

  [[-6.  1.  1.]
   [-4.  1.  0.]
   [ 3.  3. -4.]]

  [[ 1. -4. -5.]
   [-3.  2. -1.]
   [ 3.  2.  3.]]]]


In [25]:
#ex 12
a = np.array([[[[1, 0, 1], [-2, 6, -2], [-5, 0, -6]], 
              [[3, 1, 0], [2, 6, 1], [-6, 5, 4]], 
              [[-6, 3, 6], [-3, 2, 3], [1, -4, -5]]],
              [[[-1, -2, 3], [-3, 6, -1], [3, 0, -4]], 
              [[-2, -5, 5], [-3, -6, -3], [-3, 4, 2]], 
              [[-3, -2, 2], [4, 2, 5], [-4, 4, 4]]], 
              [[[2, 2, 3], [3, -2, -3], [1, -3, 1]], 
              [[-2, -2, 4], [2, -4, -4], [2, 5, -4]], 
              [[-2, 5, -5], [-1, -5, 3], [-3, 4, 1]]]])
shape = (3, 3, 3, 3)
b = np.zeros(shape)
for l in range(3):
    for i in range(3):
      for j in range(3):
        for k in range(3):
            b[i][j][l][k] = a[k][i][l][j]
print(b)

[[[[ 1. -1.  2.]
   [-2. -3.  3.]
   [-5.  3.  1.]]

  [[ 0. -2.  2.]
   [ 6.  6. -2.]
   [ 0.  0. -3.]]

  [[ 1.  3.  3.]
   [-2. -1. -3.]
   [-6. -4.  1.]]]


 [[[ 3. -2. -2.]
   [ 2. -3.  2.]
   [-6. -3.  2.]]

  [[ 1. -5. -2.]
   [ 6. -6. -4.]
   [ 5.  4.  5.]]

  [[ 0.  5.  4.]
   [ 1. -3. -4.]
   [ 4.  2. -4.]]]


 [[[-6. -3. -2.]
   [-3.  4. -1.]
   [ 1. -4. -3.]]

  [[ 3. -2.  5.]
   [ 2.  2. -5.]
   [-4.  4.  4.]]

  [[ 6.  2. -5.]
   [ 3.  5.  3.]
   [-5.  4.  1.]]]]
